#!/bin/sh
## postinstall

currentUser=$(/bin/ls -l /dev/console | /usr/bin/awk '{ print $3 }')

# attempt to kill app first
launchctl unload "/Library/LaunchAgents/com.macOSUpdate.launcher.plist"

killall "macOS Update"

# load the app
launchctl load "/Library/LaunchAgents/com.macOSUpdate.launcher.plist"

# unload the daemon
launchctl unload "/Library/LaunchDaemons/com.macOSUpdate.daemon.plist"

# kill damons
killall daemonHandler

# load the damon
#sudo "/usr/local/macOSUpdate/macOS Update.app/Contents/Resources/daemonHandler" &
launchctl load "/Library/LaunchDaemons/com.macOSUpdate.daemon.plist"

exit 0

